customhost = "employee.ccved0rmz6ie.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tehguangyong-employee"
customregion = "us-east-1"
